server:
  port: 8080

spring:
  data:
    mongodb:
      authentication-database: "admin"
      host: "mongo"
      database: "book-service-db"
      username: "root"
      password: "secret"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY-HOST}:8761/eureka/