server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/users_db
    username: root
    password: secret

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
