version: "3.8"
services:

  config-server:
    build: 
      context: ../api-config-server
    image: config-server:latest
    networks: 
      - spring-boot-microservice
    ports:
      - 8888:8888
    environment: 
      SPRING_PROFILES_ACTIVE: docker
      DISCOVERY_HOST: api-discovery

  api-discovery:
    build:
      context: ../library-api-discovery
    image: library-api-discovery:latest
    networks: 
      - spring-boot-microservice
    ports: 
      - 8761:8761

  user-service:
    build:
      context: ../user-service
    image: user-service:latest
    networks:
      - spring-boot-microservice
    ports:
      - "10080:8080"
    environment: 
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: users_db
      DISCOVERY_HOST: api-discovery
  
  book-service:
    build:
      context: ../book-service
    image: book-service:latest
    networks:
      - spring-boot-microservice
    ports:
      - "10081:8080"
    environment: 
      SPRING_PROFILES_ACTIVE: docker
      DISCOVERY_HOST: api-discovery
    
  library-service:
    build: 
      context: ../library-service
    image: library-service:latest
    networks: 
      - spring-boot-microservice
    ports: 
      - "10082:8080"
    environment: 
      SPRING_PROFILES_ACTIVE: docker
      BOOK_SERVICE_HOST: book-service
      USER_SERVICE_HOST: user-service
      DISCOVERY_HOST: api-discovery

networks:
  spring-boot-microservice:
    driver: bridge
