version: "3.8"
services:
  user-service:
    build:
      context: ../user-service
    image: user-service:latest
    networks:
      - spring-boot-microservice
    ports:
      - "10080:8080"
    environment: 
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_HOST: users-mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: users_db
  
  book-service:
    build:
      context: ../book-service
    image: book-service:latest
    networks:
      - spring-boot-microservice
    ports:
      - "10081:8080"
    environment: 
      SPRING_PROFILES_ACTIVE: docker
    
  library-service:
    build: 
      context: ../library-service
    image: library-service:latest
    networks: 
      - spring-boot-microservice
    ports: 
      - "10082:8080"
    environment: 
      SPRING_PROFILES_ACTIVE: docker

networks:
  spring-boot-microservice:
    driver: bridge
