version: "3.8"
services: 

  mysql:
    image: mysql:5.7
    volumes:
      - users-mysql-data:/var/lib/mysql
    ports: 
      - 13306:3306
    networks: 
      - spring-boot-microservice
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: users_db

  mongo:
    image: mongo
    restart: always
    volumes: 
      - books-mongodb-data:/data/db
    ports:
      - 27017:27017
    networks: 
      - spring-boot-microservice
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9001:8081
    networks: 
      - spring-boot-microservice
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret

volumes:
  users-mysql-data:
  books-mongodb-data:

networks:
  spring-boot-microservice:
    driver: bridge